php onb\uonb\user_structure.php db=migration school_id=93 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\93.log 
php onb\uonb\user_structure.php db=migration school_id=129 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\129.log 
php onb\uonb\user_structure.php db=migration school_id=271 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\271.log 
php onb\uonb\user_structure.php db=migration school_id=607 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\607.log 
php onb\uonb\user_structure.php db=migration school_id=893 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\893.log 
php onb\uonb\user_structure.php db=migration school_id=908 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\908.log 
php onb\uonb\user_structure.php db=migration school_id=927 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\927.log 
php onb\uonb\user_structure.php db=migration school_id=994 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\994.log 
php onb\uonb\user_structure.php db=migration school_id=1022 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1022.log 
php onb\uonb\user_structure.php db=migration school_id=1054 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1054.log 
php onb\uonb\user_structure.php db=migration school_id=1156 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1156.log 
php onb\uonb\user_structure.php db=migration school_id=1404 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1404.log 
php onb\uonb\user_structure.php db=migration school_id=1555 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1555.log 
php onb\uonb\user_structure.php db=migration school_id=1578 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1578.log 
php onb\uonb\user_structure.php db=migration school_id=1586 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1586.log 
php onb\uonb\user_structure.php db=migration school_id=1588 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1588.log 
php onb\uonb\user_structure.php db=migration school_id=1592 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1592.log 
php onb\uonb\user_structure.php db=migration school_id=1594 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1594.log 
php onb\uonb\user_structure.php db=migration school_id=1595 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1595.log 
php onb\uonb\user_structure.php db=migration school_id=1599 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1599.log 
php onb\uonb\user_structure.php db=migration school_id=1606 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1606.log 
php onb\uonb\user_structure.php db=migration school_id=1620 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1620.log 
php onb\uonb\user_structure.php db=migration school_id=1622 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1622.log 
php onb\uonb\user_structure.php db=migration school_id=1639 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1639.log 
php onb\uonb\user_structure.php db=migration school_id=1641 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1641.log 
php onb\uonb\user_structure.php db=migration school_id=1656 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1656.log 
php onb\uonb\user_structure.php db=migration school_id=1661 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1661.log 
php onb\uonb\user_structure.php db=migration school_id=1669 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1669.log 
php onb\uonb\user_structure.php db=migration school_id=1672 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1672.log 
php onb\uonb\user_structure.php db=migration school_id=1686 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1686.log 
php onb\uonb\user_structure.php db=migration school_id=1687 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1687.log 
php onb\uonb\user_structure.php db=migration school_id=1703 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1703.log 
php onb\uonb\user_structure.php db=migration school_id=1706 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1706.log 
php onb\uonb\user_structure.php db=migration school_id=1713 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1713.log 
php onb\uonb\user_structure.php db=migration school_id=1718 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1718.log 
php onb\uonb\user_structure.php db=migration school_id=1740 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1740.log 
php onb\uonb\user_structure.php db=migration school_id=1741 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1741.log 
php onb\uonb\user_structure.php db=migration school_id=1746 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1746.log 
php onb\uonb\user_structure.php db=migration school_id=1758 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1758.log 
php onb\uonb\user_structure.php db=migration school_id=1776 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1776.log 
php onb\uonb\user_structure.php db=migration school_id=1781 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1781.log 
php onb\uonb\user_structure.php db=migration school_id=1786 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1786.log 
php onb\uonb\user_structure.php db=migration school_id=1803 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1803.log 
php onb\uonb\user_structure.php db=migration school_id=1807 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1807.log 
php onb\uonb\user_structure.php db=migration school_id=1809 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1809.log 
php onb\uonb\user_structure.php db=migration school_id=1817 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1817.log 
php onb\uonb\user_structure.php db=migration school_id=1821 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1821.log 
php onb\uonb\user_structure.php db=migration school_id=1824 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1824.log 
php onb\uonb\user_structure.php db=migration school_id=1832 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1832.log 
php onb\uonb\user_structure.php db=migration school_id=1837 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1837.log 
php onb\uonb\user_structure.php db=migration school_id=1842 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1842.log 
php onb\uonb\user_structure.php db=migration school_id=1843 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1843.log 
php onb\uonb\user_structure.php db=migration school_id=1849 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1849.log 
php onb\uonb\user_structure.php db=migration school_id=1853 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1853.log 
php onb\uonb\user_structure.php db=migration school_id=1861 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1861.log 
php onb\uonb\user_structure.php db=migration school_id=1863 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1863.log 
php onb\uonb\user_structure.php db=migration school_id=1864 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1864.log 
php onb\uonb\user_structure.php db=migration school_id=1872 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1872.log 
php onb\uonb\user_structure.php db=migration school_id=1874 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1874.log 
php onb\uonb\user_structure.php db=migration school_id=1879 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1879.log 
php onb\uonb\user_structure.php db=migration school_id=1882 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1882.log 
php onb\uonb\user_structure.php db=migration school_id=1886 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1886.log 
php onb\uonb\user_structure.php db=migration school_id=1893 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1893.log 
php onb\uonb\user_structure.php db=migration school_id=1903 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1903.log 
php onb\uonb\user_structure.php db=migration school_id=1904 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1904.log 
php onb\uonb\user_structure.php db=migration school_id=1908 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1908.log 
php onb\uonb\user_structure.php db=migration school_id=1920 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1920.log 
php onb\uonb\user_structure.php db=migration school_id=1921 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1921.log 
php onb\uonb\user_structure.php db=migration school_id=1926 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1926.log 
php onb\uonb\user_structure.php db=migration school_id=1937 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1937.log 
php onb\uonb\user_structure.php db=migration school_id=1938 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1938.log 
php onb\uonb\user_structure.php db=migration school_id=1948 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1948.log 
php onb\uonb\user_structure.php db=migration school_id=1952 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1952.log 
php onb\uonb\user_structure.php db=migration school_id=1953 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1953.log 
php onb\uonb\user_structure.php db=migration school_id=1955 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1955.log 
php onb\uonb\user_structure.php db=migration school_id=1959 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1959.log 
php onb\uonb\user_structure.php db=migration school_id=1963 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1963.log 
php onb\uonb\user_structure.php db=migration school_id=1971 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1971.log 
php onb\uonb\user_structure.php db=migration school_id=1974 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1974.log 
php onb\uonb\user_structure.php db=migration school_id=1976 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1976.log 
php onb\uonb\user_structure.php db=migration school_id=1980 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1980.log 
php onb\uonb\user_structure.php db=migration school_id=1985 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1985.log 
php onb\uonb\user_structure.php db=migration school_id=1991 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1991.log 
php onb\uonb\user_structure.php db=migration school_id=1993 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\1993.log 
php onb\uonb\user_structure.php db=migration school_id=2002 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2002.log 
php onb\uonb\user_structure.php db=migration school_id=2004 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2004.log 
php onb\uonb\user_structure.php db=migration school_id=2009 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2009.log 
php onb\uonb\user_structure.php db=migration school_id=2013 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2013.log 
php onb\uonb\user_structure.php db=migration school_id=2014 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2014.log 
php onb\uonb\user_structure.php db=migration school_id=2019 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2019.log 
php onb\uonb\user_structure.php db=migration school_id=2020 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2020.log 
php onb\uonb\user_structure.php db=migration school_id=2029 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2029.log 
php onb\uonb\user_structure.php db=migration school_id=2030 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2030.log 
php onb\uonb\user_structure.php db=migration school_id=2041 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2041.log 
php onb\uonb\user_structure.php db=migration school_id=2048 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2048.log 
php onb\uonb\user_structure.php db=migration school_id=2050 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2050.log 
php onb\uonb\user_structure.php db=migration school_id=2057 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2057.log 
php onb\uonb\user_structure.php db=migration school_id=2058 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2058.log 
php onb\uonb\user_structure.php db=migration school_id=2064 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2064.log 
php onb\uonb\user_structure.php db=migration school_id=2068 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2068.log 
php onb\uonb\user_structure.php db=migration school_id=2069 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2069.log 
php onb\uonb\user_structure.php db=migration school_id=2072 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2072.log 
php onb\uonb\user_structure.php db=migration school_id=2077 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2077.log 
php onb\uonb\user_structure.php db=migration school_id=2078 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2078.log 
php onb\uonb\user_structure.php db=migration school_id=2088 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2088.log 
php onb\uonb\user_structure.php db=migration school_id=2091 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2091.log 
php onb\uonb\user_structure.php db=migration school_id=2097 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2097.log 
php onb\uonb\user_structure.php db=migration school_id=2103 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2103.log 
php onb\uonb\user_structure.php db=migration school_id=2104 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2104.log 
php onb\uonb\user_structure.php db=migration school_id=2116 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2116.log 
php onb\uonb\user_structure.php db=migration school_id=2123 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2123.log 
php onb\uonb\user_structure.php db=migration school_id=2124 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2124.log 
php onb\uonb\user_structure.php db=migration school_id=2164 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2164.log 
php onb\uonb\user_structure.php db=migration school_id=2175 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2175.log 
php onb\uonb\user_structure.php db=migration school_id=2180 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2180.log 
php onb\uonb\user_structure.php db=migration school_id=2181 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2181.log 
php onb\uonb\user_structure.php db=migration school_id=2183 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2183.log 
php onb\uonb\user_structure.php db=migration school_id=2186 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2186.log 
php onb\uonb\user_structure.php db=migration school_id=2190 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2190.log 
php onb\uonb\user_structure.php db=migration school_id=2194 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2194.log 
php onb\uonb\user_structure.php db=migration school_id=2214 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2214.log 
php onb\uonb\user_structure.php db=migration school_id=2226 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2226.log 
php onb\uonb\user_structure.php db=migration school_id=2228 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2228.log 
php onb\uonb\user_structure.php db=migration school_id=2234 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2234.log 
php onb\uonb\user_structure.php db=migration school_id=2249 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2249.log 
php onb\uonb\user_structure.php db=migration school_id=2280 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2280.log 
php onb\uonb\user_structure.php db=migration school_id=2289 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2289.log 
php onb\uonb\user_structure.php db=migration school_id=2294 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2294.log 
php onb\uonb\user_structure.php db=migration school_id=2299 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2299.log 
php onb\uonb\user_structure.php db=migration school_id=2309 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2309.log 
php onb\uonb\user_structure.php db=migration school_id=2347 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2347.log 
php onb\uonb\user_structure.php db=migration school_id=2357 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2357.log 
php onb\uonb\user_structure.php db=migration school_id=2360 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2360.log 
php onb\uonb\user_structure.php db=migration school_id=2362 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2362.log 
php onb\uonb\user_structure.php db=migration school_id=2363 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2363.log 
php onb\uonb\user_structure.php db=migration school_id=2367 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2367.log 
php onb\uonb\user_structure.php db=migration school_id=2368 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2368.log 
php onb\uonb\user_structure.php db=migration school_id=2369 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2369.log 
php onb\uonb\user_structure.php db=migration school_id=2370 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2370.log 
php onb\uonb\user_structure.php db=migration school_id=2383 type=live mongo=y debug=1 mail=saurabhchhabra018@gmail.com >> D:\logs\uonb\2383.log 